name: Check Identifier Files
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9.4'
      - name: 'Install JSONSchema'
        run: pip install jsonschema
      - name: 'Validate Identifier Files'
        run: python scripts/validate.py
      