name: Check Identifier Files
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9.4'
      - run: |
          pip install jsonschema
          python scripts/validate.py